### ISSUE TITLE
Re-structure module 4 (analyze latent)

### ISSUE THREAD

**Issue by ri-heme** [RasmussenLab/MOVE#40]
To match the style of modules 1 and 5 (encode data and identify associations, respectively), this module needs to be refactored.

## Task List

- [ ] Define config schema (add visualization targets as fields)
- [ ] Create new module and function
- [ ] Create example config YAML
- [ ] Add to main entry point
